language: node_js
dist: trusty
node_js:
- node
- '5'
- '5.0'
- '4'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
- iojs
- iojs-v2.0.0
- iojs-v1.5.0
- iojs-v1.0.0
script: npm run test-travis
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
